;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        paredit-forward
        paredit-forward-kill-word
        paredit-forward-slurp-sexp
        paredit-open-round
        paredit-open-square
        paredit-raise-sexp
        ))

(setq mc/cmds-to-run-once
      '(
        ))
